### ISSUE TITLE
libgcc.a missing on x86_64 systems ?

### ISSUE THREAD

**Issue by nevat** [kubilus1/gendev#6]
Installed gendev without problems. 

Create a new project with skeleton directory (with cp) and made a "hello world" in C when I run "make" ends with this error:

/opt/toolchains/gen//m68k-elf/bin/m68k-elf-gcc  -o out.elf -T /opt/toolchains/gen//ldscripts/sgdk.ld -nostdlib   boot/sega.o /opt/toolchains/gen//m68k-elf/lib/libmd.a /opt/toolchains/gen//m68k-elf/lib/gcc/m68k-elf/_/libgcc.a    main.o   -L/opt/toolchains/gen//m68k-elf/lib -L/opt/toolchains/gen//m68k-elf/lib/gcc/m68k-elf/_ -L/opt/toolchains/gen//m68k-elf/m68k-elf/lib -lmd -lnosys 
m68k-elf-gcc: error: /opt/toolchains/gen//m68k-elf/lib/gcc/m68k-elf/_/libgcc.a: No existe el fichero o el directorio (<- File not found in spanish)
Makefile:121: recipe for target 'out.elf' failed
make: *_\* [out.elf] Error 1

Looking a bit, I see that libgcc.a is in lib64 directory (I'm in a x86-64 machine). Any way to fix this ?

**Comment by kubilus1** [comment]
If you copy libgcc.a into the location the Makefile is looking for, does everything work correctly?

**Comment by kubilus1** [comment]
I've updated the project to check for AMD64 in the skeleton Makefile.  Pull the latest code and give it a shot.

**Comment by nevat** [comment]
Binutils has updated ? Now crash on compilation

**
gcc -DHAVE_CONFIG_H -I. -I../../binutils-2.24/gas  -I. -I../../binutils-2.24/gas -I../bfd -I../../binutils-2.24/gas/config -I../../binutils-2.24/gas/../include -I../../binutils-2.24/gas/.. -I../../binutils-2.24/gas/../bfd -DLOCALEDIR="\"/opt/toolchains/gen/m68k-elf/share/locale\""  -W -Wall -Wstrict-prototypes -Wmissing-prototypes -Wshadow -Werror -g -O2 -MT subsegs.o -MD -MP -MF .deps/subsegs.Tpo -c -o subsegs.o ../../binutils-2.24/gas/subsegs.c
In file included from ../../binutils-2.24/gas/as.h:95:0,
                 from ../../binutils-2.24/gas/subsegs.c:25:
../../binutils-2.24/gas/subsegs.c: In function ‘subseg_change’:
../bfd/bfd.h:304:75: error: right-hand operand of comma expression has no effect [-Werror=unused-value]

---

**Comment by nevat** [comment]
Hum... that's strange.

Binutils compilation crashes on Debian 8 and Fedora 22, but works well on Mint 17.2 (all x86_64). 

On Debian 8 a compilation with this order works well:

./configure --prefix=/rute --target=m68k-elf --disable-nls
make
make install

I'll do more tests.

**Comment by nevat** [comment]
On openSUSE 12.3 compiles and works well. Seems a the problem with the gcc shipped in some distributions.

You can close the ticket.

**Comment by kubilus1** [comment]
Will close. it looks like others have opened a duplicate ticket as well
